### ISSUE TITLE
Wo kann man den Status einsehen?

### ISSUE THREAD

**Issue by skerbis** [alexplusde/hello#1]

**Comment by alexplusde** [comment]
Was meinst du mit "Status"?

**Comment by skerbis** [comment]
wo werden die Logs gespeichert?

**Comment by alexplusde** [comment]
Die Logs werden in einer Datenbank gespeichert. Dieses Addon ist noch weit weg vom Produktiveinsatz, die Ausgabe der Logs erfolgt momentan von Hand.

**Comment by alexplusde** [comment]
Eher prototypisch umgesetzt.

**Comment by skerbis** [comment]
Du kannst mit PRs von mir rechnen

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/42518763-e32bd75c-8462-11e8-8da0-d13d836972aa.png)

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/42520960-eb5b5542-8467-11e8-92be-29bf9f6e00a4.png)

(aktuell)
