### ISSUE TITLE
rex_socket

### ISSUE THREAD

**Issue by Hirbod** [alexplusde/hello#13]
Sollten nicht lieber Redaxo-Utils verwendet werden? Der große Vorteil von rex_socket ist, dass es praktisch auf jedem Server funktioniert. Hier ist cURL Voraussetzung und es fehlt auch ein Fallback . z.B. file_get_contents.

Ich würde vorschlagen, die rex_socket Class zu nutzen, mir ist keine Serverumgebung bekannt, wo es noch nicht lief.

https://github.com/alexplusde/hello/blob/3177a910b8026a76128798a44d2a1bb70e5d1204/plugins/server/lib/hello.cronjob.php#L11

**Comment by alexplusde** [comment]
@Hirbod kann rex_socket mehrere Anfragen parallel ausführen?

**Comment by Hirbod** [comment]
Ich glaube nicht, es wird für jede URL eine neue Socket-Verbindung geöffnet, under the hood wird cURL aber vermutlich ebenfalls nichts anderes machen, es muss sowieso jede URL Aufrufen, wird dazu ggf. aber nur einen Handle nutzen. Ich denke, wir reden hier von minimaler Performance oder RAM Ersparnis, mit Rex-Socket aber über maximale Kompatibilität.

**Comment by alexplusde** [comment]
http://php.net/manual/de/function.curl-multi-init.php 

> Erlaubt die asynchrone Verarbeitung mehrerer cURL-Handles.

**Comment by alexplusde** [comment]
Wenn du mir eine performante Alternative nennst, mit der ich 50 verschiedene Abrufe gleichzeitig machen kann ohne einen Timeout zu bekommen, sehe ich eine Änderung als machbar.

**Comment by Hirbod** [comment]
Vllt mal @gharlan fragen - er hat die class gebaut.

**Comment by alexplusde** [comment]
```
requires:
    php:
        extensions: [curl]
```
?

**Comment by gharlan** [comment]
jupp

**Comment by tbaddade** [comment]
Welches AddOn betrifft das denn genau? Die Client- oder Serverversion?

| Version | |
| ------------- |:-------------|
| Client | rex_socket (maximale Serverkompatibilität), damit könnte man dann auch ein REX4 AddOn adaptieren |
| Server | curl oder rex_socket (wobei ich die socket Variante auch bevorzugen würde) |

Damit es weniger verwirrt, sollte man Hello eventuell in zwei separate AddOns aufteilen?

**Comment by alexplusde** [comment]
Das betrifft die Server-Version.
Der Client ist das Addon, der Server ein Plugin. Somit ist eine Aufteilung da und es gibt keine Notwendigkeit, den Server zu installieren.

**Comment by alexplusde** [comment]
Ich würde vorerst bei der Einteilung bleiben, wie sie ist, außer es gibt Gründe, die eine Unterteilung notwendig machen.
